@startjson "import-parameter-json"
{
    "left_image" : {
        "kind":"rgb_camera",
        "size" : {
            "width_pix" : 1242,
            "height_pix" : 375
        }
        ,
        "focal_length" : {
            "fx_pix" : 9.895267e+02,
            "fy_pix" : 9.878386e+02
        }
        ,
        "optical_center" : {
            "cx_pix" : 7.020000e+02,
            "cy_pix" : 2.455590e+02
        }
        ,
        "field_of_view" : {
            "fovx_deg" : 90
        }
        ,
        "sensor_position" : {
            "x_m" : 0.06,
            "y_m" : 1.65,
            "z_m" : 0.27
        }
        ,
        "projection_matrix" : [
            [7.215377e+02, 0.000000e+00, 6.095593e+02, 4.485728e+01],
            [0.000000e+00, 7.215377e+02, 1.728540e+02, 2.163791e-01],
            [0.000000e+00, 0.000000e+00, 1.000000e+00, 2.745884e-03]
        ]
    }
    ,
    "right_image" : {
        "kind":"rgb_camera",
        "size" : {
            "width_pix" : 1242,
            "height_pix" : 375
        }
        ,
        "focal_length" : {
            "fx_pix" : 9.037596e+02,
            "fy_pix" : 9.019653e+02
        }
        ,
        "optical_center" : {
            "cx_pix" : 6.957519e+02,
            "cy_pix" : 2.242509e+02
        }
        ,
        "field_of_view" : {
            "fovx_deg" : 90
        }
        ,
        "sensor_position" : {
            "x_m" : -0.54,
            "y_m" : 1.65,
            "z_m" : 0.27
        }
        ,
        "projection_matrix" : [
            [7.215377e+02, 0.000000e+00, 6.095593e+02, -3.395242e+02],
            [0.000000e+00, 7.215377e+02, 1.728540e+02, 2.199936e+00],
            [0.000000e+00, 0.000000e+00, 1.000000e+00, 2.729905e-03]
        ]
    }
    ,

    "depth" : {
        "kind":"lidar",
        "sensor_position" : {
            "x_m" : 0.0,
            "y_m" : 1.73,
            "z_m" : 0.0
        }
        ,
        "coordinate_system":{
            "xyz_from" : "yzx",
            "x" : 1,
            "y" : 2,
            "z" : 0
        }
    }
}
@endjson